?state.x77
library("corrplot")
library("corrgram")
cor(state.x77[,c("Population","Illiteracy","Income","Frost","Murder")])
corrplot(cor(state.x77[,c("Population","Illiteracy","Income","Frost","Murder")]), method = "circle")
corrgram(state.x77[,c("Population","Illiteracy","Income","Frost","Murder")])
state <- as.data.frame(state.x77,row.names = state.x77)
head(state)
fit <- lm(Murder ~ Population + Illiteracy + Income + Frost, state)
summary(fit)
fit2 <- lm(Murder ~ Population + Illiteracy,state)
summary(fit2)
cor(state.x77[,c("Population","Illiteracy","Income","Frost","Murder")])
anova(fit,fit2)
fit3 <- step(fit, direction = "backward")
summary(fit3)
predict(fit2,list(Population = 10000, Illiteracy = 1.1))
fit4 <- lm(Murder ~ Population + Illiteracy + Population:Income,state)
summary(fit4)

titanic <- read.csv("titanic(2).csv")
head(titanic)
library(dplyr)
sum(is.na(titanic))
titanic$age[is.na(titanic$age)] <- mean(titanic$age, na.rm = TRUE)
titanic$fare[is.na(titanic$fare)] <- mean(titanic$fare, na.rm = TRUE)
titanic <- titanic[which(!is.na(titanic$survived)),]
titanic$sex = ifelse(titanic$sex=="male", 1, 0)

row_number = sort(sample(nrow(titanic), nrow(titanic)*.7))
test<-titanic[-row_number,] 
train<-titanic[row_number,]
lfit <- glm(survived ~ sex + age + fare, family=binomial, data=train)
summary(lfit)
test2 <- subset(test,select=c(4,5,9))
results <- predict(lfit, newdata=test2,type='response')
results <- ifelse(results > 0.5,1,0)
mean(results == test$survived)
library("caret")
confusionMatrix(as.factor(results), as.factor(test$survived))


lfit <- glm(sex ~ survived + age + fare, family=binomial, data=train)
summary(lfit)
test2 <- subset(test,select=c(2,5,9))
results <- predict(lfit, newdata=test2,type='response')
results <- ifelse(results > 0.5,1,0)
mean(results == test$sex)
library("caret")
confusionMatrix(as.factor(results), as.factor(test$sex))
