dataset1 <- read.csv(file = "AirPass.csv", header = TRUE)
dataset1
datasetTS <- ts(dataset1$Passengers,start=c(1949,01),end=c(1960,12),frequency = 12)
datasetTS
library("forecast")
sum(is.na(dataset1$PassengersMissing))
datasetM <- ts(dataset1$PassengersMissing,start=c(1949,01),end=c(1960,12),frequency = 12)
rm(dataset1)
library("imputeTS")
datasetComplete1<-na_interpolation(datasetM)
datasetComplete2<-na_ma(datasetM, k=4, weighting = "exponential")
datasetComplete3<-na_kalman(datasetM)
datasetComplete4<-na_kalman(datasetM, model="auto.arima")
test<- cbind(datasetTS,datasetM,datasetComplete1,datasetComplete2,datasetComplete3,datasetComplete4)
plot(datasetTS)
seasonplot(datasetTS)
?ma
par(mfrow=c(2,2))
plot(datasetTS)
plot(ma(datasetTS,3))
plot(ma(datasetTS,7))
plot(ma(datasetTS,13))
par(mfrow=c(1,1))
logPass<- log(datasetTS)
plot(logPass)
fit<- stl(logPass, s.window="periodic")
plot(fit)
fc <- ses(datasetTS,h=10)
autoplot(datasetTS) + autolayer(fc)
train <- subset(datasetTS, end = length(datasetTS) - 20)
fcses <- ses(train, h = 20)
autoplot(train) + autolayer(fcses)
fcnaive <- naive(train, h = 20)
autoplot(train) + autolayer(fcnaive)
accuracy(fcses, datasetTS)
accuracy(fcnaive,datasetTS)
fcholt <- holt(datasetTS, h=10)
summary(fcholt)
plot(fcholt)
fchw<- hw(datasetTS, h=10)
plot(fchw)
fchwm<- hw(datasetTS,h=10,seasonal = "multiplicative")
plot(fchwm)
fcholtT <- holt(train, h=20)
fchwT<- hw(train, h=20)
fchw1T<- hw(train, h=20, seasonal="multiplicative")
accuracy(fcholtT, datasetTS)
accuracy(fchwT, datasetTS)
accuracy(fchw1T, datasetTS)
autoplot(datasetTS) + autolayer(fcholtT$mean) + autolayer(fchwT$mean) + autolayer(fchw1T$mean)
