library(forecast)
data <- read.csv("iphonesales.csv", header = TRUE)
ipts <- ts(data$Sales,frequency = 4)
tsdisplay(ipts)
plot(diff(ipts))
arm <- arima(ipts,order=c(0,1,0))
plot(forecast(arm))
checkresiduals(arm)
arm2 <- arima(ipts,order=c(2,1,0))
plot(forecast(arm2))
checkresiduals(arm2)
afit <- auto.arima(ipts)
plot(forecast(afit,h=4))
plot(forecast(afit,h=8))
plot(forecast(afit,h=12))
summary(afit)
checkresiduals(afit)
